### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by araeubig** [Web3-Pi/rpi-lcd-dashboard#2]
After testing the repo on a bookworm full install, i installed with your advises new on a fresh bookworm lite install.

I get the error "No module named 'psutil' - after trying a lot of things (all with a fresh install) i 'am actually without a solution.

Do you have any ideas / hints for me?

**Comment by cmd0s** [comment]
Hello,

To specifically check this, I just installed Bookworm Lite 64-bit on my Raspberry Pi 5. After following the steps in my ReadMe.md step by step, everything worked as expected.

Are you using the create_service.sh script?

**Comment by araeubig** [comment]
I found the 'bug': In my test files i doesn't do the python update - based on the prior install it was working perfect but on the clean system it doesn't work. After changing the run.sh file it works on the clean system great too.
